### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by chrisclarkson** [ernstlab/ChromTime#4]
Hi I think I have formatted my files properly this time:

```
1       3000211 3000312 HWI-D00436:416:CCFY2ANXX:3:1303:18089:47589/1   27      +
1       3000228 3000327 HWI-D00436:416:CCFY2ANXX:4:1108:15962:53423/1   42      +
1       3000228 3000327 HWI-D00436:416:CCFY2ANXX:4:1108:15962:53423/2   42      -
1       3000239 3000339 HWI-D00436:416:CCFY2ANXX:3:1303:18089:47589/2   27      -
1       3000349 3000449 HWI-D00436:416:CCFY2ANXX:3:1304:13359:3723/2    26      +
1       3000420 3000520 HWI-D00436:416:CCFY2ANXX:3:1304:13359:3723/1    26      -


python ~/ChromTime/ChromTime.py -a W4.bed KO4.bed -c INPUT_WT.bed INPUT_KO.bed -o H3K9ME3_4 -p development -t 4 -g mm9
[2018-11-17 15:03:17] Options:
 {'aligned_fnames': ['W4_ME3.bed',
                    'K4_ME3.bed'],
 'bin_size': 200,
 'broad': False,
 'control_fnames': ['INPUT_WT_ME3.bed',
                    'INPUT_KO_ME3.bed'],
 'data_fname': None,
 'fdr_for_decoding': 0.05,
 'genome': 'mm9',
 'keep_fixed_priors': False,
 'merge_peaks': False,
 'min_dynamic_prior': 0,
 'min_expected_reads': 1,
 'min_gap': 600,
 'mode': 'narrow',
 'model_fname': None,
 'n_threads': 4,
 'n_training_examples': 10000,
 'order_fname': None,
 'out_dir': 'H3K9ME3_4',
 'output_empty_blocks': False,
 'output_signal_files': False,
 'p_value_extend': 0.15,
 'prefix': 'development',
 'q_value_seed': 0.05,
 'shift': 100,
 'skip_training': False,
 'use_broad_window_for_background': False}
[2018-11-17 15:03:17] Estimating initial block boundaries
[2018-11-17 15:03:18] Reading reads from: 
W4_ME3.bed
[2018-11-17 15:06:09] Total reads used for peak calling: 0
[2018-11-17 15:06:09] Skipped reads outside of chromosome boundaries: 104676202
[2018-11-17 15:06:09] Reading reads from: 
INPUT_WT_ME3.bed
[2018-11-17 15:09:26] Total reads used for peak calling: 0
[2018-11-17 15:09:26] Skipped reads outside of chromosome boundaries: 120787050
```

But this time I'm getting the error:

```
Traceback (most recent call last):
  File "/home/cc16956/ChromTime/ChromTime.py", line 865, in <module>
    use_broad_window_for_background=args.use_broad_window_for_background)
  File "/home/cc16956/ChromTime/ChromTime.py", line 537, in determine_block_boundaries
    use_broad_window_for_background=use_broad_window_for_background)
  File "/home/cc16956/ChromTime/ChromTime.py", line 112, in call_peaks
    pseudo_one_read = float(min_expected_reads * total_background_reads) / total_foreground_reads
ZeroDivisionError: float division by zero
```

Is there something wrong with my data? I had originally prepared them from bamfiles with the command `bamtobed` from the 'bedtools' software... the output is as shown above.... do I not have sufficient coverage or something?

**Comment by chrisclarkson** [comment]
based on the above I have done the following:

I changed your ChromTime.py script as follows:

I changed your `call_peaks` function-

```
print(min_expected_reads, 'min_expected_reads')
print(total_background_reads,'total_background_reads')
print(total_foreground_reads,'total_foreground_reads')
print(float(min_expected_reads * total_background_reads), 'ratio')
pseudo_one_read = float(min_expected_reads * total_background_reads) / float(total_foreground_reads)
```
the output of which is:

```
(1, 'min_expected_reads')
(0, 'total_background_reads')
(0, 'total_foreground_reads')
(0.0, 'ratio')
```

followed by the same error....

I checked the number of lines in each of the files I'm using- this produces numbers like: 122529570
However your script says it skips reads that fall outside the given mapped genome- your script is skipping portions large numbers of reads: 

`Skipped reads outside of chromosome boundaries: 104676202`

I am sure that the data I'm using are from mm9 which I have specified in the command....

Could this be the source of the problem?

**Comment by pfiziev** [comment]
Hi Chris,

Thanks for bringing this up! The problems seems to be that the chromosome names in your input file do not follow the standard chromosome names from UCSC (e.g. you have 1, 2, 3 etc instead of chr1, chr2, chr3 ..). ChromTime considers only reads that map to chromosomes that are defined in the corresponding genome file that has all chromosome sizes (in your case "genomes/mm9.txt"). For this reason, ChromTime filters out all your reads. I added a check from this in the code that prints out a more descriptive warning message. 

Could you please: 

1) download the latest ChromTime code, and 

2) Either add the prefix "chr" to all the entries in the first column of your input bed files, or create a new genome file (say "genomes/mm9_custom.txt") and edit out all the "chr" prefixes from the chromosomes there and run ChromTime with "-g mm9_custom" instead of "-g mm9"

Also, with H3K9me3 you may want to use the -m broad option, because this mark tends to cover broader regions as compared to more narrow marks such as H3K4me3/2 and others.

**Comment by chrisclarkson** [comment]
Hi Petko,

Thanks so much for your quick replies on my questions about your package. I have finally got the output I needed.

I just was hoping to ask one more technical question- obviously not as an issue this time 😊:


Now that I have the output I am trying to choose what to do with it- I just need to make sure that I know what each output file is...

So I input the following command:

python ~/ChromTime/ChromTime.py -a W4.bed KO4.bed -c INPUT_WT.bed INPUT_KO.bed -o H3K9ME3_4 -p development -t 4 -g mm9

and out of this I got the following files:


development.WT.bed.gz

development.K4.bed.gz

development.ChromTime_full_output.bed.gz


I just want to ask- as I only have 2 timepoints (WT vs KO), is there much point in this type of analysis? From initially looking at the output it seems as though there are very few loci (although there are some..) where my mark of interest spread... Do I need more timepoints in order to do a viable analysis this way?

Kind regards,

Chris

________________________________
