### ISSUE TITLE
output predicted starts and ends very narrow

### ISSUE THREAD

**Issue by chrisclarkson** [ernstlab/ChromTime#5]
Hello-
I recently used your package to analyse histone marks across time using the data from Bing Ren's lab on ENCODE (here is the [link](https://www.encodeproject.org/matrix/?type=Experiment&status=released&assay_slims=DNA+binding&replicates.library.biosample.donor.organism.scientific_name=Mus+musculus&lab.title=Bing+Ren%2C+UCSD) to the used data) and wanted to ask you about the output of your software.
Basically, the output predicted start-end coordinates are very narrow. Should I expect this?
I did this for both H3K27me3 and H3K9me3 with and without the `broad_marks` option with no observable difference.

Please see below an exemplary pipeline

```
tissue=hindbrain       
target=H3K27me3        
stage=16.5    
r=1_1     
acc=ENCFF613JON
bowtie -t -v 2 -p 5 -S -m 1 /storage/projects/ReferenceGenomes/BowtieIndexes/mm9 ${target}_${r}_${tissue}_${stage}_${acc}.fastq $
{target}_${r}_${tissue}_${stage}.sam
samtools view -bS ${target}_${r}_${tissue}_${stage}.sam > ${target}_${r}_${tissue}_${stage}.bam
samtools sort ${target}_${r}_${tissue}_${stage}.bam > ${target}_${r}_${tissue}_${stage}_s.bam
samtools index ${target}_${r}_${tissue}_${stage}_s.bam  
bamToBed -i ${target}_${r}_${tissue}_${stage}_s.bam > ${target}_${r}_${tissue}_${stage}.bed
```
I take a look at the output bed file:
```
chr1    3000554 3000590 HWI-ST216:479:C4K8UACXX:1:1107:7493:18632       255     +
chr1    3000696 3000732 HWI-ST216:479:C4K8UACXX:1:1202:4057:76584       255     +
chr1    3000703 3000739 HWI-ST216:479:C4K8UACXX:1:2210:7064:87372       255     -
chr1    3000974 3001010 HWI-ST216:479:C4K8UACXX:1:1113:19876:92349      255     -
```
I then prepare to use ChromeTime:
input
```
H3K27me3_hindbrain_10.5_sorted.bed      ../Control/Control_hindbrain_10.5_sorted.bed
H3K27me3_hindbrain_11.5_sorted.bed      ../Control/Control_hindbrain_11.5_sorted.bed
H3K27me3_hindbrain_12.5_sorted.bed      ../Control/Control_hindbrain_12.5_sorted.bed
H3K27me3_hindbrain_13.5_sorted.bed      ../Control/Control_hindbrain_13.5_sorted.bed
H3K27me3_hindbrain_14.5_sorted.bed      ../Control/Control_hindbrain_14.5_sorted.bed
H3K27me3_hindbrain_15.5_sorted.bed      ../Control/Control_hindbrain_15.5_sorted.bed
H3K27me3_hindbrain_16.5_sorted.bed      ../Control/Control_hindbrain_16.5_sorted.bed
```
command (tried with and without the broad peaks option)
`python ~/ChromTime/ChromTime.py -i ${tissue}_${target}_input.txt -o ChromTime_narrow -p development -t 4 -g mm9`

Finally I take the last column from `development.ChromTime_full_output.bed` - which looks like the following:
```
chr1 predicted_starts:3702400,3702400,3702400,3702400,3702400,3702400,3702400 predicted_ends:3702400,3702400,3702400,3703200,3703200,3703200,3703200
chr1 predicted_starts:6372400,6372400,6372400,6372400,6372400,6372400,6372400 predicted_ends:6374800,6374800,6374800,6374800,6374800,6374800,6374800
chr1 predicted_starts:20735800,20735800,20735800,20735800,20735800,20735800,20735800 predicted_ends:20736400,20736400,20736400,20736400,20736400,20736400,20736400
```
So the first thing that I notice is that the numbers change very little across development.
I plotted a histogram of the width of predicted peaks across timepoints:

![image](https://user-images.githubusercontent.com/26774207/69958022-d3253800-14fb-11ea-94f3-4a3b2b6e83c7.png)

As you can see they don't change at all really.

Finally I wrote a script to search for where the peaks had spread across  the time points:
The rare few rows where the peak widths did change- I then plotted in IGV.

![image](https://user-images.githubusercontent.com/26774207/69963056-48e2d100-1507-11ea-8c85-7dfe8c3c6687.png)

As you can see from the  exemplary loci above the time points- in the cases where the mark does change- it doesn't change by very much. Furthermore it only seems to spread in one direction (i.e. either  in the 5' or 3' direction but not both).
Is this expected?

I was hoping that you might  be able to spot anything in my pipeline that could potentially be the reason for the lack of cases where the mark changes?

**Comment by pfiziev** [comment]
Hi Chris,

Thank you for your feedback! It could be that the method is calling too many steady boundaries on this dataset (i.e. being too conservative), bit it is hard to tell from the above figures. Can you please show the raw signal in RPKM units for the peaks at each time point in the last figure? 

Also - are there any places that are expected to change H3K27me3 signal (say near differentially expressed genes, etc). Can you look if peaks are expanding or contracting there?

Thanks
Pete

**Comment by chrisclarkson** [comment]
Hey- Thanks very much for the reply!
1. I am not actually very experienced with RPKM values and could not find a way to calculate them without remapping the data with Cufflinks... I'm willing to do this if you need this info to answer the question (as a quick way- I tried checking the header of the mapped BAM files but they don't contain any info about RPKM values).

2. As for genes, I don't have any genes in mind where this should be happening- I can find one if you need. 
I checked to see if the places where H3K27me3 was spreading were generally enriched at genes with a fisher test:

```
bedtools fisher -a changed_sites_sorted.bed -b mm9_ensembl_genes.bed -g mm9.genome
# Number of query intervals: 27933
# Number of db intervals: 69483
# Number of overlaps: 20246
# Number of possible intervals (estimated): 104961
# phyper(20246 - 1, 27933, 104961 - 27933, 69483, lower.tail=F)
# Contingency Table Of Counts
#_________________________________________
#           |  in -b       | not in -b    |
#     in -a | 20246        | 7687         |
# not in -a | 49237        | 27791        |
#_________________________________________
# p-values for fisher's exact test
left	right	two-tail	ratio
1	1.4758e-151	2.5424e-151	1.487
```
So from the above results it would seem that the spreading of H3K27me3 does occur at genes. However I'm a little concerned as the places where it spread are never wide enough to cover a whole gene. See below the sites where H3K27me3 are a fraction of the size of most genes:
![image](https://user-images.githubusercontent.com/26774207/70321431-388c6800-181f-11ea-8a5f-05351107ee27.png)

However I'd have to check that it's not happening specifically at the promoter of these genes. See below an exemplary case where the spread mark could indeed be covering a promoter of the gene ASPM:
![image](https://user-images.githubusercontent.com/26774207/70321528-712c4180-181f-11ea-962a-7c0c56482d42.png)

**Comment by pfiziev** [comment]
You can generate the signal files with ChromTime by using the "--output-signal-files" option (which is turned off by default). For this purpose, you can just re-run ChromTime with all other options as you did before and add "--output-signal-files" to the command line. This will generate one wiggle file for each time point with the RPKM values across the whole genome. Then you can visualize these files in IGV (you may want to convert them to tdf format with igvtools to make IGV work faster, but the .wig files from ChromTime should also work). We can get more understanding after we inspect visually the signal and the peaks called by ChromTime, similarly to how we did for this dataset: https://genome.ucsc.edu/cgi-bin/hgTracks?db=mm9&lastVirtModeType=default&lastVirtModeExtraState=&virtModeType=default&virtMode=0&nonVirtPosition=&position=chr9%3A37327280%2D37406212&hgsid=781841465_A0URpIP6zOVDPe8TforDjIa3igsY

**Comment by chrisclarkson** [comment]
Hi again- So I ran it again as you asked- the output is as follows:
![image](https://user-images.githubusercontent.com/26774207/70539868-2c284800-1b5c-11ea-8a5e-47ea1d2af3cf.png)
The above pictures are organised in pairs where the upper one is an earlier time point and the lower of the two is a later time point.
The top 2 (dark blue) are the wig file visualisations from the *RPKM.wig, the middle two in green are from *READ_COUNTS.wig and the bottom two in torquoise are from *EXPECTED.wig.

If you need something else let me know.
Thanks Chris

**Comment by pfiziev** [comment]
Great! Can you please put RPKM, read counts, expected _and_ the peaks called by ChromTime in the same figure, so we can see how signal changes relate to the predicted peaks by ChromTime? 

Also - make sure that each pair of signal tracks is on the same scale (i.e. the y-axes have the same min and max values, which is a setting in IGV; also - ideally you should show the highest values in those tracks, but you can play a bit to see what works best). Otherwise, it is difficult to compare between signal tracks. 

It would be good to inspect some places where you expect K27me3 to expand or shrink. Also - show some of the predicted expansions and contractions.

**Comment by chrisclarkson** [comment]
Ok so from the latest I renormalised the scale of each track. The height of the bars generally appears to be going down in the time points..
Then compared them to the old peaks that I showed you (produced by the script that I wrote that isolated peaks where the width changed):
![image](https://user-images.githubusercontent.com/26774207/70611419-16b72a80-1bfd-11ea-9d33-66cdd53c94a7.png)

Then I looked through the peak files that were created just from ChromTime's raw output:
![image](https://user-images.githubusercontent.com/26774207/70611599-5b42c600-1bfd-11ea-87a0-bed4663ce0f2.png)

The colour scheme above is: 

- red is the '*block_boundaries.bed' (there was only one of these files i.e. one for the time point 10.5 and not for any of the other time points), 
- light-blue is for the '*significant_bins.bed' (upper= earlier timepoint, lower=later timepoint) , 
- grey is *timepoint_predictions.bed (upper= earlier timepoint, lower=later timepoint) 

I also looked at this same locus zoomed in:
![image](https://user-images.githubusercontent.com/26774207/70612226-76620580-1bfe-11ea-9e50-7ef6034ea444.png)

**Comment by pfiziev** [comment]
Thanks! It seems hard to tell what is going on here, except that the method is estimating steady boundaries. ChIP-seq data for H3K27me3 and H3K9me3 was in my experience somewhat noisier compared to other marks, which can cause the method to call conservatively steady boundaries. Are there any predicted expansions or contractions at all? Can you please count how many peaks are there for each predicted class (e.g. S-S-S-S vs E-E-.. etc). You can do this easily by using the full output file from ChromTime with something like:

zcat [file-name].ChromTime_full_output.bed.gz | cut -f5 | tr '/' '\n' | sort | uniq -c

where you replace [file-name] accordingly

**Comment by chrisclarkson** [comment]
```
     
cat development.ChromTime_full_output.bed | cut -f5 | tr '/' '\n' | sort | uniq -c
1 C-C-C-S-S-S

      3 C-C-S-S-S-S
      4 C-S-C-S-S-S
      4 C-S-C-x-x-x
      1 C-S-E-S-S-S
      1 C-S-S-C-S-S
      1 C-S-S-C-x-x
      1 C-S-S-S-C-S
    714 C-S-S-S-S-S
    117 C-x-x-x-x-x
      1 E-C-S-S-S-S
      5 E-E-S-S-S-S
     37 E-S-E-S-S-S
      1 E-S-S-E-S-S
   5495 E-S-S-S-S-S
      6 S-C-C-S-S-S
      4 S-C-C-x-x-x
      2 S-C-S-C-S-S
      1 S-C-S-C-x-x
      1 S-C-S-S-C-S
      4 S-C-S-S-C-x
    371 S-C-S-S-S-S
    165 S-C-x-x-x-x
      1 S-E-C-x-x-x
    258 S-E-S-S-S-S
      4 S-S-C-C-S-S
      7 S-S-C-C-x-x
     16 S-S-C-S-C-S
     29 S-S-C-S-C-x
   2235 S-S-C-S-S-S
      1 S-S-C-S-S-x
      1 S-S-C-S-x-x
   2830 S-S-C-x-x-x
    884 S-S-E-S-S-S
    188 S-S-S-C-S-S
    260 S-S-S-C-x-x
      2 S-S-S-E-S-S
    344 S-S-S-S-C-S
    618 S-S-S-S-C-x
 477513 S-S-S-S-S-S
    646 S-S-S-S-S-x
    268 S-S-S-S-x-x
   2821 S-S-S-x-x-x
    165 S-S-x-x-x-x
    117 S-x-x-x-x-x
      3 x-E-C-x-x-x
     60 x-E-E-S-S-S
      1 x-E-S-S-C-x
   8945 x-E-S-S-S-S
      1 x-E-S-S-S-x
      1 x-S-S-S-C-x
   8999 x-S-S-S-S-S
      1 x-S-S-S-S-x
      3 x-S-S-x-x-x
   4370 x-x-E-S-S-S
   4364 x-x-S-S-S-S
     53 x-x-x-E-S-S
     53 x-x-x-S-S-S

```

**Comment by pfiziev** [comment]
These counts actually show that there is a substantial number of predicted expansions and contractions (every label that has an 'E' or an 'C' in it). You can grep individual instances from the full output file if you want to look at them in the browser. These expansions and contractions may contain also creation and removal of peaks, which are not shown as red or blue in IGV, but just as regular grey peaks in the time point that has significant signal. Please let me know if this makes sense and if you have more questions.

**Comment by chrisclarkson** [comment]
Ok thanks very much so I did the following:

```
grep 'E-' development.ChromTime_full_output.bed > expansions.bed
for i in {10..16}; 
do 
intersectBed -a development_H3K27me3_midbrain_${i}.5_sorted.significant_bins.bed \
-b expansions.bed -u >  \
expansions_development_H3K27me3_midbrain_${i}.5_sorted.significant_bins.bed; 
done
```
![image](https://user-images.githubusercontent.com/26774207/70997343-c0e6f480-20cc-11ea-9910-9631e383aa60.png)

Is this what  you were looking for?
I did the same for regions that contracted- contracting regions seem a bit more stable and last throughout differentiation.

**Comment by pfiziev** [comment]
I am closing this issue. Please, let me know if you have any further questions!
